#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 SuperNovae Studio <contact@supernovae.studio>
#
# cert.py — the full conformance certificate, projected.
#
# verify.py proves an entry VALID (hash + oracle). This script goes where
# only Nika can: it runs the reference engine's static analysis on every
# pinned artifact and projects the result into two derived surfaces —
#
#   certs/<publisher>/<name>/<version>.json   the machine certificate
#   CATALOG.md                                the human storefront
#
# The certificate answers, BEFORE a single run: can this workflow exec?
# which tools does it invoke? what does it cost? does a secret leak or
# egress? what permits boundary does it need? No other workflow registry
# can generate this column — the engine's audit-before-run IS the moat.
#
# Derived, never authored: entries stay immutable; certs regenerate from
# the pinned bytes + a PINNED engine version. CI runs --check (projection
# parity, the house pattern) — a cert that drifts from what the engine
# actually proves turns the board red.
#
# Usage:
#   python3 scripts/cert.py --write        # regenerate certs/ + CATALOG.md
#   python3 scripts/cert.py --check        # drift gate (exit 1 on diff)
# Env:
#   NIKA_BIN        path to the nika binary (MUST be ENGINE_VERSION below)
#   OFFLINE_ROOT    resolve sources from local checkouts (mirrors · air-gap)

import hashlib
import json
import os
import pathlib
import subprocess
import sys
import tomllib
import urllib.request

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from verify import is_broad_permits  # noqa: E402 — one source for the ⚠ predicate

ROOT = pathlib.Path(__file__).resolve().parent.parent
# The cert is only comparable if every generator runs the SAME engine.
ENGINE_VERSION = "0.103.0"


def fetch_source(repo: str, rev: str, path: str) -> bytes:
    offline = os.environ.get("OFFLINE_ROOT")
    if offline:
        # A mirror dir sits directly under the root; confirm it so a repo name
        # of `..` cannot escape (matches verify.py's guard · R6 also rejects it).
        root = pathlib.Path(offline).resolve()
        local = (root / repo.split("/")[1]).resolve()
        if local.parent != root:
            raise ValueError(f"offline repo `{repo}` escapes the mirror root {offline}")
        out = subprocess.run(["git", "-C", str(local), "show", f"{rev}:{path}"],
                             capture_output=True)
        if out.returncode != 0:
            raise FileNotFoundError(out.stderr.decode()[:120])
        return out.stdout
    url = f"https://raw.githubusercontent.com/{repo}/{rev}/{path}"
    req = urllib.request.Request(url, headers={"User-Agent": "nika-registry-cert"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def engine_cert(nika: str, wf: pathlib.Path) -> dict:
    """One artifact through the engine's static analysis → the cert dict."""
    check = subprocess.run([nika, "check", str(wf), "--json"],
                           capture_output=True, text=True)
    report = json.loads(check.stdout)
    permits = subprocess.run([nika, "check", str(wf), "--infer-permits"],
                             capture_output=True, text=True).stdout.strip()

    cost = report.get("cost", {})
    cert = report.get("certificate", {})
    reqs = report.get("requirements", {})
    return {
        "clean": report.get("clean", False),
        "llm_calls": cert.get("llm_calls", {}).get("constant"),
        "effect_calls": cert.get("effect_calls", {}).get("constant"),
        # The inputs a run MUST be given — a required `vars:` with no default.
        # Part of "see what it needs before it runs": even a mock/offline
        # preview fails NIKA-VAR-001 without these, so the consume hand-off
        # warns instead of suggesting a command that cannot run.
        "vars_required": sorted(reqs.get("vars_required", []) or []),
        "cost_usd": {
            "bounded_total": cost.get("bounded_total_usd"),
            "has_unbounded": cost.get("has_unbounded"),
        },
        "secret_leaks": report.get("secret_leaks", []),
        "secret_egresses": report.get("secret_egresses", []),
        "capability_escapes": report.get("capability_escapes", []),
        "permits_boundary": permits,
        # A machine-readable flag for agents: does this artifact hold an
        # unbounded grant (exec / any-tool)? "clean" + "broad" together say
        # "no policy violation, but the cert cannot vet what the grant does".
        "broad": is_broad_permits(permits),
    }


def load_entries():
    for p in sorted(ROOT.glob("registry/**/*.toml")):
        e = tomllib.loads(p.read_text())
        rel = p.relative_to(ROOT)
        yield rel, e


def render_catalog(rows: list) -> str:
    lines = [
        "# Catalog",
        "",
        "<!-- GENERATED by scripts/cert.py --write — do not hand-edit. Every",
        "     column below is the ENGINE's static analysis of the pinned bytes",
        f"     (nika {ENGINE_VERSION} · re-proven in CI). The point: you see what",
        "     a workflow CAN DO — exec, tools, cost, secrets — before it runs. -->",
        "",
        f"Certified by `nika {ENGINE_VERSION}` static analysis · re-proven on every PR and nightly.",
        "",
        "⚠ = an **unbounded grant** (`exec: true` runs any program · `*` allows any",
        "tool). The cert proves the effect stays inside the *declared* permits — it",
        "cannot vet what a permitted exec or tool actually does. ⚠ means *read the",
        "workflow before you run it*; it is not a verdict of unsafe.",
        "",
        "| Artifact | Version | What it does | Exec? | Tools | LLM calls | Cost/run | Cert |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        cost = "unbounded — set `max_tokens`" if r["cert"]["cost_usd"]["has_unbounded"] else f"≤ ${r['cert']['cost_usd']['bounded_total']:.2f}"
        exec_flag = "yes ⚠" if "exec: true" in r["cert"]["permits_boundary"] else "no"
        tools = ", ".join("⚠ any" if t == "*" else t for t in r["tools"]) if r["tools"] else "—"
        lines.append(
            f"| **{r['name']}** | {r['version']} | {r['description']} "
            f"| {exec_flag} | {tools} | {r['cert']['llm_calls']} | {cost} "
            f"| [cert](certs/{r['publisher']}/{r['name']}/{r['version']}.json) |"
        )
    broad = sum(1 for r in rows if is_broad_permits(r["cert"]["permits_boundary"]))
    lines += [
        "",
        f"{len(rows)} artifacts re-proven · {broad} carry an unbounded grant (⚠).",
        "",
        "Install: read the entry under `registry/`, fetch the pinned bytes, verify",
        "the sha256, run `nika check` yourself — the cert is re-derivable, never",
        "trusted. `nika add` (engine roadmap) automates exactly these steps.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    if mode not in ("--write", "--check"):
        print(f"cert.py: unknown mode {mode!r} (--write | --check)", file=sys.stderr)
        return 2
    nika = os.environ.get("NIKA_BIN", "nika")
    ver = subprocess.run([nika, "--version"], capture_output=True, text=True).stdout.strip()
    if ENGINE_VERSION not in ver:
        print(f"cert.py: NIKA_BIN is `{ver}` — certs pin nika {ENGINE_VERSION} "
              "(bump ENGINE_VERSION deliberately, then --write)", file=sys.stderr)
        return 2

    tmp = ROOT / ".cert-tmp"
    tmp.mkdir(exist_ok=True)
    rows, drift = [], False
    for rel, e in load_entries():
        body = fetch_source(e["source"]["repo"], e["source"]["rev"], e["source"]["path"])
        if hashlib.sha256(body).hexdigest() != e["integrity"]["sha256"]:
            print(f"cert.py: {rel} bytes do not match the pinned sha256 — run verify.py", file=sys.stderr)
            return 2
        wf = tmp / f"{e['name']}-{pathlib.Path(e['source']['path']).name}"
        wf.write_bytes(body)
        cert = engine_cert(nika, wf)

        tools = sorted({
            line.strip().strip('",')
            for line in cert["permits_boundary"].splitlines()
            for line in line.split("[")[-1].split("]")[0].split(",")
            if line.strip().strip('",').startswith("nika:")
        }) if "tools:" in cert["permits_boundary"] else []

        doc = {
            "schema": 1,
            "engine": ENGINE_VERSION,
            "entry": str(rel),
            "sha256": e["integrity"]["sha256"],
            "certificate": cert,
        }
        out = ROOT / "certs" / e["publisher"] / e["name"] / f"{e['version']}.json"
        rendered = json.dumps(doc, indent=2, sort_keys=True) + "\n"
        if mode == "--write":
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(rendered)
            print(f"✓ cert {e['name']}@{e['version']} · clean={cert['clean']} · llm={cert['llm_calls']}")
        elif not out.is_file() or out.read_text() != rendered:
            print(f"✗ cert drift · {out.relative_to(ROOT)}", file=sys.stderr)
            drift = True
        rows.append({"name": e["name"], "version": e["version"], "publisher": e["publisher"],
                     "description": e["description"], "tools": tools, "cert": cert})

    catalog = render_catalog(rows)
    cat_path = ROOT / "CATALOG.md"
    if mode == "--write":
        cat_path.write_text(catalog)
        print(f"✓ CATALOG.md · {len(rows)} artifacts")
    elif not cat_path.is_file() or cat_path.read_text() != catalog:
        print("✗ CATALOG.md drift", file=sys.stderr)
        drift = True

    if mode == "--check" and not drift:
        print(f"✓ certs + catalog in sync ({len(rows)} artifacts · nika {ENGINE_VERSION})")
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
