#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 SuperNovae Studio <contact@supernovae.studio>
#
# project_pack.py — the first-party entries are a PROJECTION of the spec's
# canonical pack, never a hand-kept third list.
#
# Before this, the registry seed was authored by hand while the spec's
# examples/manifest.yaml was the real source of first-party workflows —
# the exact triple-source drift class the 2026-07-06 audit killed on the
# counts. Now: add a showcase to the spec, re-run this, it publishes. The
# registry cannot diverge from the pack because it derives from it.
#
# Scope (operator lock 2026-07-06): the SHOWCASES only (t1-t4 · the real
# installable artifacts). Foundation examples (01-hello …) are tutorials,
# not things you `nika add` — they stay out. Community entries stay
# authored by PR (this only owns registry/workflows/supernovae-st/).
#
# Derived, gated: --write regenerates, --check fails on drift in CI. The
# entry version tracks the pack_version's MAJOR.MINOR.PATCH; a new pack
# version mints new (immutable) entries, the old ones stay resolvable.
#
# Usage:
#   python3 scripts/project_pack.py --write   # regenerate the seed entries
#   python3 scripts/project_pack.py --check   # drift gate
# Env:
#   NIKA_SPEC_DIR   a nika-spec checkout (the pack source) — REQUIRED
#                   the pinned rev is read from its git HEAD

import hashlib
import os
import pathlib
import subprocess
import sys

try:
    import yaml
except ImportError:
    print("project_pack: pyyaml required", file=sys.stderr)
    sys.exit(2)

ROOT = pathlib.Path(__file__).resolve().parent.parent
PUBLISHER = "supernovae-st"
SPEC_REPO = "supernovae-st/nika-spec"

ENTRY = '''# GENERATED by scripts/project_pack.py from the nika-spec pack —
# do not hand-edit. A first-party showcase is a projection of the
# canonical pack (examples/manifest.yaml), never a parallel list.
# Re-generate: python3 scripts/project_pack.py --write
schema = 1
type = "workflow"
name = "{name}"
publisher = "{publisher}"
version = "{version}"
description = "{desc}"
license = "Apache-2.0"
spec = "nika/v1"

[source]
repo = "{repo}"
rev = "{rev}"
path = "{path}"

[integrity]
sha256 = "{sha}"

[cert]
oracle = "nika-spec conformance/runner.py @ {rev7}"
conformance = "pass"
'''


def semver(pack_version: str) -> str:
    # "0.1.0-draft" → "0.1.0" — the registry version tracks the pack's.
    return pack_version.split("-")[0]


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    spec_dir = os.environ.get("NIKA_SPEC_DIR")
    if not spec_dir:
        print("project_pack: NIKA_SPEC_DIR unset (the pack source)", file=sys.stderr)
        return 2
    spec = pathlib.Path(spec_dir)
    pin = (ROOT / "SPEC_PIN").read_text()
    rev = next(l.strip() for l in pin.splitlines() if l.strip() and not l.startswith("#"))

    def at_rev(path: str) -> bytes:
        out = subprocess.run(["git", "-C", str(spec), "show", f"{rev}:{path}"],
                             capture_output=True)
        if out.returncode != 0:
            print(f"project_pack: {path}@{rev[:9]} unreadable — is NIKA_SPEC_DIR a "
                  f"nika-spec clone containing SPEC_PIN's commit?", file=sys.stderr)
            sys.exit(2)
        return out.stdout

    manifest = yaml.safe_load(at_rev("examples/manifest.yaml").decode())
    version = semver(manifest["pack_version"])

    def showcase_identity(sc: dict, body: bytes) -> tuple[str, str]:
        # Three manifest eras, one projector. The pin decides which
        # era is read — the projector accepts all, never guesses.
        #   pre-0.106: workflow: <id> + top-level description
        #   0.106–0.1.0: workflow: {id, description}
        #   0.2.0:       name: + file: (description lives in the file banner)
        if "workflow" in sc:
            wf = sc["workflow"]
            name = wf["id"] if isinstance(wf, dict) else wf
            desc = ((wf.get("description") if isinstance(wf, dict) else None)
                    or sc.get("description") or "")
        else:
            name = sc.get("name") or pathlib.Path(sc["file"]).stem
            desc = sc.get("description") or ""
            if not desc:
                prev = ROOT / "registry/workflows" / PUBLISHER / name / "0.1.0.toml"
                if prev.is_file():
                    for line in prev.read_text().splitlines():
                        if line.startswith("description"):
                            desc = line.split("=", 1)[1].strip().strip('"')
                            break
            if not desc:
                parts = []
                for line in body.decode().splitlines():
                    if not line.startswith("#"):
                        if parts:
                            break
                        continue
                    text = line[1:].strip()
                    if (not text or text.startswith("SPDX")
                            or text.startswith("yaml-language-server")
                            or text.startswith("showcase")):
                        continue
                    parts.append(text)
                    if len(" ".join(parts)) >= 80:
                        break
                desc = " ".join(parts)
        return name, desc.replace('"', "'")[:200]

    generated = {}  # rel_path -> rendered
    for sc in manifest["showcase"]:
        path = sc["file"]
        body = at_rev(path)
        # The registry pins the REAL bytes a consumer downloads (banner
        # included) — NOT the manifest's sha256_16, which hashes the LEAN
        # display text (comment banner stripped for the site/docs render).
        # Two legitimate contracts; the registry's is the install one.
        sha = hashlib.sha256(body).hexdigest()
        name, desc = showcase_identity(sc, body)
        rel = pathlib.Path("registry/workflows") / PUBLISHER / name / f"{version}.toml"
        generated[rel] = ENTRY.format(name=name, publisher=PUBLISHER, version=version,
                                      desc=desc, repo=SPEC_REPO, rev=rev, path=path,
                                      sha=sha, rev7=rev[:9])

    # The set of first-party workflow entries this projector OWNS.
    owned = set((ROOT / "registry/workflows" / PUBLISHER).glob("*/*.toml"))
    owned_rel = {p.relative_to(ROOT) for p in owned}

    drift = False
    if mode == "--write":
        for rel, rendered in generated.items():
            out = ROOT / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(rendered)
        # Remove first-party entries no longer in the pack (renamed/dropped)
        # for the CURRENT version only — older versions stay (immutable).
        for rel in owned_rel - set(generated):
            if rel.parts[-1] == f"{version}.toml":
                (ROOT / rel).unlink()
                (ROOT / rel).parent.rmdir() if not any((ROOT / rel).parent.iterdir()) else None
        print(f"✓ projected {len(generated)} first-party showcases @ {version} · pack {rev[:9]}")
        # Stage 2 rides automatically: index.json/llms.txt/badges DERIVE
        # from the entries this just rewrote — a pin bump that stopped
        # here shipped a drift-red PR (2026-07-10, caught by CI). One
        # --write means EVERY stage.
        r = subprocess.run([sys.executable, str(ROOT / "scripts" / "index.py"), "--write"])
        if r.returncode != 0:
            print("✗ stage 2 (index.py --write) failed — the projection is HALF-done", file=sys.stderr)
            return 1
        return 0

    for rel, rendered in generated.items():
        out = ROOT / rel
        if not out.is_file() or out.read_text() != rendered:
            print(f"✗ drift · {rel} — run scripts/project_pack.py --write", file=sys.stderr)
            drift = True
    stale = {rel for rel in owned_rel - set(generated) if rel.parts[-1] == f"{version}.toml"}
    for rel in stale:
        print(f"✗ orphan · {rel} not in the pack — run --write", file=sys.stderr)
        drift = True
    if not drift:
        print(f"✓ {len(generated)} first-party showcases in sync with the pack @ {version}")
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
